version: "1.0.0"
services:
  heist_bot:
    container_name: "heist_bot"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    entrypoint: /heist
    depends_on:
      - mongodb

  mongodb:
    container_name: "heist_mongo"
    image: mongo:latest
    env_file: ./.env_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_USERNAME}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    
volumes:
  mongodb_data_container:

